# Generated by Django 2.1.5 on 2019-05-02 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=1000)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/profile_pics/')),
                ('gender', models.CharField(default='', max_length=5)),
                ('interests', models.ManyToManyField(blank=True, to='posts.Cartegory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
