# Generated by Django 2.1.5 on 2019-05-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='following',
            new_name='follower',
        ),
    ]
