# Generated by Django 2.1.5 on 2019-05-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190504_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_pic',
            field=models.ImageField(blank=True, upload_to='images/background_pics/'),
        ),
    ]
