# Generated by Django 2.2.2 on 2020-05-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_background_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_background_pic',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_profile_pic',
            field=models.URLField(blank=True),
        ),
    ]
