# Generated by Django 2.2.2 on 2020-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200522_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_pic',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
    ]
