# Generated by Django 2.2.2 on 2020-05-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200522_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
