# Generated by Django 2.1.5 on 2019-05-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='save_for_future',
        ),
    ]
