# Generated by Django 2.1.5 on 2019-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190505_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post_name',
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/post_images/'),
        ),
        migrations.DeleteModel(
            name='postImage',
        ),
    ]
