# Generated by Django 2.1.5 on 2019-05-07 20:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190507_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_body',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
