# Generated by Django 2.1.5 on 2019-05-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_body',
            new_name='post_heading',
        ),
    ]
