# Generated by Django 2.1.5 on 2019-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190507_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_heading',
            field=models.CharField(default='', max_length=40),
        ),
    ]
