# Generated by Django 2.1.5 on 2019-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190507_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartegory',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/cartegory_images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
