# Generated by Django 2.2.2 on 2020-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20190510_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
