# Generated by Django 2.2.2 on 2020-05-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200525_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartegory',
            name='newImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
